<html>
  <head>
    <title>Test Persistent Amqphp</title>

    <style type="text/css">

      #container {
        float: none;
      }

      #controls {
        float: left;
        padding: 0;
        border: 0;
        margin: 0;
      }

      #data {
        float: left;
        background: #A8C0D8;
      }

      #connections {
        /* Connections floating menu */
        background: #BEE2E7;
      }

      label {
        display: block;
      }

      #connections input {
        vertical-align: bottom;
        position: relative;
      }

      #new-conn {
        /* New connection form */
        background: #4F57AA;
      }

      #channels {
        /* Channels container */
        background: #72818B;
      }

      .channel {
        /* Channel container */
        background: #72818B;
        border: 1px solid black;
      }

      .consumer {
        /* Consumer container */
        background: #8F002E;
      }

      #new-channel {
        /* New channel form */
        background: #454857;
      }

      #methods {
        background: #788F7D;
      }

      #send {
        background: #77775E;
      }

      #receive {
        background: #DCDABB;
      }
    </style>

  </head>
  <body>

    <h1>Amqphp in web servers: <?php echo getmypid() ?></h1>


    <?php foreach ($this->messages as $m) { ?>
    <div id="messages">
      <span><?php echo $m; ?></span>
    </div>
    <?php } ?>


    <div id="container">
      <div id="controls">

        <div id="connections">
          <h2>Connections</h2>
          <!-- TODO: Turn this is to a floater! -->
          <ul>
            <?php if ($this->conns->getConnections()) { foreach ($this->conns->getConnections() as $k => $conn) { ?>
            <li>
              <form method="POST">
                ID: <?php echo $k ?>
                <input type="hidden" name="action" value="remove-connection"/>
                <input type="hidden" name="name" value="<?php echo $k ?>"/>
                <input type="submit" value="Remove"/>
              </form>
            </li>
            <?php } } else { ?>
            <li>
              <strong>There are no open connections at this time.</strong>
            </li>
            <?php } ?>
          </ul>
          <div id="new-conn">
            <h2>Create a new connection</h2>
            <form method="POST">
              <input type="hidden" name="action" value="new-connection"/>
              <label>
                Persistent
                <input type="checkbox" name="persistent" checked="checked"/>
              </label>

              <label>
                Name
                <input type="text" name="name" value="test1"/>
              </label>
              <label>
                Url
                <input type="text" name="socketParams[url]" value="tcp://rabbit1:5672"/>
              </label>
              <label>
                VHost
                <input type="text" name="vhost" value="robin"/>
              </label>
              <label>
                Username
                <input type="text" name="username" value="testing"/>
              </label>
              <label>
                Password
                <input type="text" name="userpass" value="letmein"/>
              </label>

              <input type="submit" value="Go!"/>
            </form>
          </div>
        </div>



        <div id="channels">
          <h2>Channels</h2>

          <?php if (! $this->conns->hasChannels()) { ?>
            <strong>There are no channels open at this time.</strong>
          <?php } else { ?>
          <?php foreach ($this->conns->getConnections() as $k => $conn) { if ($chans = $conn->getChannels()) { foreach ($chans as $k2 => $chan) { ?>
          <div class="channel">
            <!-- Repeats -->
            <ul>
              <li>Channel: <?php echo $k ?>.<?php echo $k2 ?></li>
            </ul>
            <form method="POST">
              <input type="hidden" name="action" value="remove-channel"/>
              <input type="hidden" name="channel" value="<?php echo $k2 ?>"/>
              <input type="hidden" name="connection" value="<?php echo $k ?>"/>
              <input type="submit" value="Remove Channel" id="channel-remove"/>
            </form>

            <?php if ($cTags = $chan->getConsumerTags()) { foreach ($cTags as $cTag) { ?>
            <h3>Consumers</h3>
            <div class="consumer">
              <!-- Repeats -->
              <form method="POST">
                <span class="consumer-tag">Consumer: <?php echo $cTag ?></span>
                <span class="consumer-class">Class: DemoConsumer</span>
                <input type="hidden" name="action" value="remove-consumer"/>
                <input type="hidden" name="connection" value="<?php echo $k ?>"/>
                <input type="hidden" name="channel" value="<?php echo $k2 ?>"/>
                <input type="hidden" name="consumer-tag" value="<?php echo $cTag ?>"/>
                <input type="submit" value="Remove Consumer"/>
              </form>
            </div>
            <?php } } else { ?>
              <strong>There are no consumers attached to this channel</strong>
            <?php } ?>

            <h3>Add Consumer</h3>
            <div class="new-consumer">
              <form method="POST">
                <input type="hidden" name="action" value="new-consumer"/>
                <input type="hidden" name="connection" value="<?php echo $k ?>"/>
                <input type="hidden" name="channel" value="<?php echo $k2 ?>"/>
                <label>
                  Consumer Class
                  <select name="impl">
                    <option value="DemoConsumer">DemoConsumer</option>
                    <option value="DemoPConsumer">DemoPConsumer</option>
                  </select>
                </label>
                <input type="submit" value="Add Consumer"/>
              </form>
            </div>
          </div>
          <?php } } } ?> <!-- End foreach channel / if hasChannels / foreach channels -->
          <?php } ?><!-- End of "if has channels" -->


          <?php if ($conns = $this->conns->getConnections()) { ?>
          <div id="new-channel">
            <h2>Add new Channel</h2>
            <form method="POST">
              <input type="hidden" name="action" value="new-channel"/>
              <label>
                Connection
                <select name="connection">
                  <?php foreach ($conns as $k => $conn) { ?>
                    <option value="<?php echo $k  ?>"><?php echo $k ?></option>
                  <?php } ?>
                </select>
              </label>
              <label>
                Persistent
                <input type="radio" name="persistent" value="yes" checked="checked"/>
              </label>
              <label>
                Temporary
                <input type="radio" name="persistent" value="no"/>
              </label>
              <input type="submit" value="Add Channel"/>
            </form>
          </div>
          <?php } ?>
        </div><!-- End Channels section -->




        <?php if ($this->conns->hasChannels()) { ?>
        <div id="send">
          <h2>Send</h2>
          <form method="POST">
            <input type="hidden" name="action" value="send"/>
            <label>
              Message
              <textarea name="message" cols="45" rows="8"></textarea>
            </label>

            <fieldset>
              <legend>Send to channels</legend>
              <?php foreach ($this->conns->getConnections() as $k => $conn) { foreach ($conn->getChannels() as $k2 => $chan) { ?>
              <label>
                Channel <?php echo $k ?>.<?php echo $k2 ?>
                <input type="checkbox" name="target[<?php echo $k ?>][]" value="<?php echo $k2 ?>"/>
              </label>
              <?php } } ?>
            </fieldset>
            <input type="submit" value="Send"/>
          </form>
        </div>
        <?php }?>


        <div id="receive">
          <h2>Receive</h2>
          <form method="POST">
            <input type="hidden" name="action" value="receive"/>

            <fieldset>
              <legend>Receive on channels</legend>
              <label>
                Conn #1
                <input type="checkbox" name="connections[1]" value="1"/>
              </label>
              <label>
                Conn #2
                <input type="checkbox" name="connections[2]" value="1"/>
              </label>
            </fieldset>
            <input type="submit" value="Receive"/>
          </form>
        </div>
      </div><!-- End of controls container -->


      <div id="data">
        <h2>Data - messages sent / received</h2>
      </div>

    </div><!-- End of data container -->


  </body>
</html>
